coston/react-super-responsive-table

lib/SuperResponsiveTable.js, src/SuperResponsiveTable.js
First of all, thanks for this responsive tables, it saved me a lot of time. Hovewer I needed to assign a className to some Td elements to apply custom styles for them. Unfortunately I have noticed you don't support it so I have added this posibility in this pull request.
Additionly I needed to pass onClick prop to Tr element, so this feature is added too.
=> Pass className prop to Td element

package.json
=> chore(package): update styled-components to version 3.1.0-3

package.json
=> chore(package): update react-live to version 1.9.2

package.json
=> chore(package): update styled-components to version 3.1.6

package.json
=> chore(package): update react-window-ui to version 1.0.1

package.json
=> chore(package): update react-live to version 1.10.1

package.json
=> chore(package): update styled-components to version 3.2.1

package.json
=> chore(package): update styled-components to version 3.2.3

README.md, dist/tableContext.js, example/bundle.js, package-lock.json, package.json, src/tableContext.js
=> Fix context error

README.md
This PR fixes a typo in the README.md file
=> Fix typo on the README.md file

.prettierrc, dist/SuperResponsiveTable.js, package.json, yarn.lock
=> chore(scripts): make scripts windows friendly

dist/SuperResponsiveTable.js, src/SuperResponsiveTable.js
Removed undefined comparison of ``<td>`` children and treat all falsy values.
It fixes #109
=> Check if children exist (treat all cases : null, undefined or empty) Fixes #109

dist/SuperResponsiveTable.js, src/SuperResponsiveTable.js, test/SuperResponsiveTable.test.js, test/__snapshots__/SuperResponsiveTable.test.js.snap
Added the rest of the props to the `<td>`element and to the distribution and created a snapshot test for it
=> #115 Added the rest of the props to the td element

README.md
- Adds @galacemiguel as a contributor
- References the projects board in contributing section
- Docs
- My code follows the code style of this project.
- If my change requires a change to the documentation I have updated the documentation accordingly.
=> docs: update contributors and contributing

.eslintrc.js, src/components/TdInner.js, test/index.test.js
=> fix: render falsy variables in td tags

src/index.d.ts
Added new file index.d.ts with typescript definition for classes Table, Tbody, Td, Th, Thead, Tr.
This definitions was created using basic definition following original .js classes and have to be updated if a definition in change or if a new exported class was added in the future.
All classes and interfaces was created to be help improved future enhancement.
I made some tests in my project using this index.d.ts on "react-super-responsive-table" and worked correctly with this new feature.
closes #200 
- New feature (non-breaking change which adds functionality)
Maybe will be interesting add in README "typescript compatible".
=> add index.d.ts typescript definition file

test/index.test.js
Add test labeled `// TODO`
- test
- My code follows the code style of this project.
- If my change requires a change to the documentation I have updated the documentation accordingly.
=> Add unique case test

README.md
Many thanks for including me here as a contributor! I just wanted to update the reference as i changed my username account.
- My code follows the code style of this project.
- If my change requires a change to the documentation I have updated the documentation accordingly.
=> Added alexandra-c to contributors

.github/workflows/nodejs-ci.yml
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- My code follows the code style of this project.
- If my change requires a change to the documentation I have updated the documentation accordingly.
=> ci: use lts

.eslintrc.js, .github/workflows/nodejs-ci.yml
=> ci: run lint
